const { parentPort } = require("worker_threads");
const vm = require("vm");
const { getClient } = require("./db/pool");

/**
 * SECURITY WARNING: Node.js VM module is NOT a security boundary
 * 
 * This sandbox provides BASIC isolation only. For production use with untrusted code:
 * 1. Use isolated-vm library instead of vm module
 * 2. Run in separate Docker containers with resource limits
 * 3. Implement network isolation and syscall filtering
 * 4. Add code analysis before execution
 * 
 * Current implementation is suitable for:
 * - Internal tools with trusted users
 * - Development/testing environments
 * - Code generated by controlled AI systems
 */

/**
 * Sandboxed Execution Evaluator
 * Runs AI-generated JavaScript with restricted access
 */
async function executeSandboxedCode(code, automationId, runId, secrets) {
  const logs = [];
  const startTime = Date.now();

  const emitLog = (type, message) => {
    logs.push({ type, message, timestamp: Date.now() - startTime });
    parentPort.postMessage({
      type: 'log',
      logType: type,
      message: message,
      time: new Date().toISOString()
    });
  };
  
  // Validate code before execution
  if (!code || typeof code !== 'string') {
    throw new Error('Invalid code: must be a non-empty string');
  }

  if (code.length > 100000) {
    throw new Error('Code too large: maximum 100KB');
  }

  // Check for dangerous patterns
  const dangerousPatterns = [
    /require\s*\(\s*['"]child_process['"]\s*\)/,
    /require\s*\(\s*['"]fs['"]\s*\)/,
    /require\s*\(\s*['"]net['"]\s*\)/,
    /process\.exit/,
    /eval\s*\(/,
    /Function\s*\(/,
  ];

  for (const pattern of dangerousPatterns) {
    if (pattern.test(code)) {
      throw new Error(`Dangerous pattern detected: ${pattern.source}`);
    }
  }

  // Custom console with rate limiting
  let logCount = 0;
  const MAX_LOGS = 1000;
  
  const sandboxConsole = {
    log: (...args) => {
      if (logCount++ < MAX_LOGS) emitLog('info', args.join(" "));
    },
    info: (...args) => {
      if (logCount++ < MAX_LOGS) emitLog('info', args.join(" "));
    },
    warn: (...args) => {
      if (logCount++ < MAX_LOGS) emitLog('warning', args.join(" "));
    },
    error: (...args) => {
      if (logCount++ < MAX_LOGS) emitLog('error', args.join(" "));
    }
  };

  // Whitelist of allowed modules
  const allowedModules = {
    'axios': require('axios'),
    'crypto': require('crypto'),
  };

  const sandboxRequire = (moduleName) => {
    if (!allowedModules.hasOwnProperty(moduleName)) {
      throw new Error(`Module '${moduleName}' is not permitted in sandbox. Allowed: ${Object.keys(allowedModules).join(', ')}`);
    }
    return allowedModules[moduleName];
  };

  // Create restricted context
  const context = {
    console: sandboxConsole,
    require: sandboxRequire,
    setTimeout: (fn, delay) => {
      if (delay > 60000) throw new Error('setTimeout delay cannot exceed 60 seconds');
      return setTimeout(fn, delay);
    },
    clearTimeout,
    Promise,
    Buffer,
    // Provide secrets in read-only manner
    SECRETS: Object.freeze({ ...secrets }),
    module: { exports: {} },
    // Prevent access to global objects
    global: undefined,
    process: undefined,
  };

  vm.createContext(context);

  try {
    emitLog('system', "Initializing sandbox environment...");
    emitLog('info', `Code size: ${code.length} bytes`);
    
    const script = new vm.Script(code, {
      filename: `automation-${automationId}.js`,
      displayErrors: true,
    });
    
    // Execute with timeout
    script.runInContext(context, { 
      timeout: 30000,
      breakOnSigint: true,
    });

    if (typeof context.module.exports.execute !== "function") {
      throw new Error("Generated code must export an 'execute' function");
    }

    emitLog('system', "Executing automation...");
    const result = await Promise.race([
      context.module.exports.execute(),
      new Promise((_, reject) => 
        setTimeout(() => reject(new Error('Execution timeout after 30s')), 30000)
      )
    ]);
    
    const duration = Date.now() - startTime;
    emitLog('success', `Execution completed in ${duration}ms`);
    
    parentPort.postMessage({ 
      type: 'complete', 
      result: { success: true, result, duration } 
    });
    
    return { success: true, result, logs, duration };
    
  } catch (err) {
    const duration = Date.now() - startTime;
    emitLog('error', `Execution failed: ${err.message}`);
    
    parentPort.postMessage({ 
      type: 'complete', 
      result: { success: false, error: err.message, duration } 
    });
    
    return { success: false, error: err.message, logs, duration };
  }
}

// Receive job from main thread
parentPort.on("message", async (data) => {
  const { runId, automationId, code, secrets } = data;
  
  let client;
  
  try {
    // Get database client
    client = await getClient();
    
    await client.query(
      `UPDATE execution_logs SET status = 'running', started_at = NOW() WHERE run_id = $1`,
      [runId]
    );

    const { success, error, logs, result, duration } = await executeSandboxedCode(
      code, 
      automationId,
      runId,
      secrets || {}
    );

    await client.query(
      `UPDATE execution_logs 
       SET status = $1, error = $2, steps_log = $3, duration = $4, completed_at = NOW() 
       WHERE run_id = $5`,
      [
        success ? 'completed' : 'failed', 
        error || null, 
        JSON.stringify(logs),
        duration / 1000, // Convert to seconds
        runId
      ]
    );
    
  } catch (err) {
    console.error('Worker error:', err);
    
    if (client) {
      try {
        await client.query(
          `UPDATE execution_logs 
           SET status = 'failed', error = $1, completed_at = NOW() 
           WHERE run_id = $2`,
          [err.message, runId]
        );
      } catch (updateErr) {
        console.error('Failed to update execution log:', updateErr);
      }
    }
    
    parentPort.postMessage({ 
      type: 'complete', 
      result: { success: false, error: err.message } 
    });
  } finally {
    if (client) {
      client.release();
    }
  }
});
